/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description 聊天接口：JWT 决定用户，conversation_id 决定该用户内的可见线程。
         */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Stream
         * @description SSE 流式聊天：子 Agent 生命周期事件 + 最终 done。
         */
        post: operations["chat_stream_api_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description 注册并直接登录（返回 token）；用户名冲突 409
         */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description 登录：返回 token；用户名/密码错误 401
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description 校验当前 token → 返回用户名（前端登录态校验用）
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stats
         * @description 当前用户差旅画像（确定性聚合，零 LLM）：次数/天数/常去城市/年度趋势。
         *
         *     页面直接拉取渲染，不经 LLM——差旅统计是结构化数据查询，不是开放生成。
         */
        get: operations["stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Memory
         * @description 当前用户记忆快照：偏好 + 行程档案（前端记忆侧栏可视化，体现 Agent 长期记忆）
         */
        get: operations["memory_api_memory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Messages
         * @description 按 conversation_id 拉回历史消息（前端箭头跳转续聊时恢复上下文）。
         */
        get: operations["messages_api_messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Trip
         * @description 取消行程（任意状态 → cancelled，保留记录不物理删除）。
         */
        post: operations["cancel_trip_api_trips__trip_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Index
         * @description React 前端入口：frontend/dist 构建产物；未构建时给出构建指引
         */
        get: operations["index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/livez": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Livez
         * @description 进程存活探针：不访问 LLM、Embedding、数据库或磁盘运行时状态。
         */
        get: operations["livez_livez_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description 只读就绪探针：配置、Postgres、RAG 语料和前端静态资产。
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description 兼容旧部署入口；语义与 readiness 一致，不再无条件返回 200。
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthRequest */
        AuthRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** AuthResponse */
        AuthResponse: {
            /** Token */
            token: string;
            /** Username */
            username: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** User Input */
            user_input: string;
            /**
             * Conversation Id
             * @default default
             */
            conversation_id: string;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Answer */
            answer: string;
            /** Intent */
            intent: string;
            /** Reason */
            reason: string;
            plan?: components["schemas"]["TripPlan"] | null;
            stats?: components["schemas"]["TravelStats"] | null;
            history?: components["schemas"]["HistoryResult"] | null;
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["KnowledgeSource"][];
            /** Policy Status */
            policy_status?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoryItinerary
         * @description 历史行程明细（结构化卡片；容忍旧数据缺字段）
         */
        HistoryItinerary: {
            /** Start Date */
            start_date?: string | null;
            /** From City */
            from_city?: string | null;
            /** To City */
            to_city?: string | null;
            /** Duration Days */
            duration_days?: number | null;
            /** Summary */
            summary?: string | null;
            /**
             * Status
             * @default 历史
             */
            status: string;
        };
        /**
         * HistoryResult
         * @description 历史查询结果（结构化；供聊天消息渲染行程卡片；空态由 answer 文本表达）
         */
        HistoryResult: {
            /**
             * Itineraries
             * @default []
             */
            itineraries: components["schemas"]["HistoryItinerary"][];
            /**
             * Preferences
             * @default []
             */
            preferences: components["schemas"]["Preference"][];
            /**
             * Direction
             * @default 历史
             */
            direction: string;
        };
        /**
         * Itinerary
         * @description 行程档案（记忆侧栏展示字段；容忍旧数据缺字段）
         */
        Itinerary: {
            /** Id */
            id?: number | null;
            /** Start Date */
            start_date?: string | null;
            /** From City */
            from_city?: string | null;
            /** To City */
            to_city?: string | null;
            /** Duration Days */
            duration_days?: number | null;
            /** Summary */
            summary?: string | null;
            /**
             * Status
             * @default 历史
             */
            status: string;
            /** Conversation Id */
            conversation_id?: string | null;
            /** People Count */
            people_count?: number | null;
            /** Return Date */
            return_date?: string | null;
            /** Purpose */
            purpose?: string | null;
        };
        /**
         * KnowledgeSource
         * @description 可追溯知识来源；与答案文本分离，供前端渲染来源卡片。
         */
        KnowledgeSource: {
            /** Evidence Id */
            evidence_id: string;
            /** Source */
            source: string;
            /** Section */
            section?: string | null;
            /** Similarity */
            similarity?: number | null;
            /**
             * Text
             * @default
             */
            text: string;
        };
        /** MemorySnapshot */
        MemorySnapshot: {
            /** Preferences */
            preferences: components["schemas"]["Preference"][];
            /** Itineraries */
            itineraries: components["schemas"]["Itinerary"][];
        };
        /** Preference */
        Preference: {
            /** Category */
            category: string;
            /** Content */
            content: string;
        };
        /**
         * TravelStats
         * @description 差旅画像（确定性聚合，零 LLM；供 /api/stats 页面展示）
         */
        TravelStats: {
            /** Has Data */
            has_data: boolean;
            /** Trips */
            trips: number;
            /** Total Days */
            total_days: number;
            /** Avg Days */
            avg_days: number;
            /** Skipped Days */
            skipped_days: number;
            /** Top Cities */
            top_cities: {
                [key: string]: unknown;
            }[];
            /** Years */
            years: {
                [key: string]: unknown;
            }[];
            /** Upcoming Trips */
            upcoming_trips: number;
        };
        /** TripDay */
        TripDay: {
            /** Date */
            date: string;
            /** Transport */
            transport: string;
            /** Hotel */
            hotel: string;
            /** Activities */
            activities: string[];
            /** Notes */
            notes: string;
        };
        /**
         * TripPlan
         * @description 结构化行程（slice 1）：/api/chat → plan；日期模糊标记由行程 Agent 附加
         */
        TripPlan: {
            /** Summary */
            summary: string;
            /** Reasons */
            reasons: string[];
            /** Days */
            days: components["schemas"]["TripDay"][];
            /**
             * Date Is Vague
             * @default false
             */
            date_is_vague: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_api_chat_stream_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_api_stats_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TravelStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_api_memory_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemorySnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    messages_api_messages_get: {
        parameters: {
            query: {
                conversation_id: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_trip_api_trips__trip_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                trip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    livez_livez_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
